apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-stress
  labels:
    app: kube-stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-stress
  template:
    metadata:
      labels:
        app: kube-stress
    spec:
      containers:
      - name: kube-stress
        image: bitqu/kubestress:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "200m"
          limits:
            cpu: "200m"
        command: [ "sh", "-c"]
        args:
        - "./kubestress"
        env:
        - name: DEPLOYMENT_NAME
          value: kube-stress
        - name: TOTAL_CPU_LOAD
          value: "1000"
        - name: PER_POD_PROCESS
          value: "1"
        - name: PER_POD_CPU_LIMIT
          value: "200"
        - name: TEST_PERIOD_SECOND
          value: "10"
