apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-stress
  labels:
    app: kube-stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-stress
  template:
    metadata:
      labels:
        app: kube-stress
    spec:
      containers:
      - name: kube-stress
        image: gcr.io/oceanex-stage/kube-stress:latest
        imagePullPolicy: Always
        command: [ "sh", "-c"]
        args:
        - "./main"
        env:
          - name: DEPLOYMENT_NAME
            value: kube-stress
          - name: TOTAL_CPU_PERCENT
            value: 100
          - name: PER_POD_PROCESS
            value: 2
          - name: TEST_PERIOD_SECOND
            value: 10
